# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='on_uat',
            field=models.BooleanField(default=False, verbose_name='On UAT'),
        ),
        migrations.AlterField(
            model_name='job',
            name='uat_passed',
            field=models.BooleanField(default=False, verbose_name='UAT passed'),
        ),
        migrations.AddField(
            model_name='job',
            name='repo',
            field=models.ManyToManyField(to='jobs.Repo'),
        ),
    ]
