# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_written_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deployed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='deployment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
