# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_job_deployed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='test_path',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
