# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20180711_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='where',
            field=models.SmallIntegerField(choices=[(1, 'local'), (2, 'UAT'), (3, 'Jenkins')], default=3),
        ),
    ]
